import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next';

const Home: NextPage<{name: string, numList: Array<string>}> = ({name, numList}) => {

  function changeToUpperCase(word: string) {
    return word.toUpperCase();
  }

  console.log(changeToUpperCase('Austin is cool!'))
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async (context) => {
  console.log(context);
  let name: string = "Austin";
  let numList: Array<number> = [1,2,3,4,5];

  return {
    props:
    {
      name: name,
      numList: numList,
    }
  }
};



export default Home


/*
TypeScript: A Static Type Checker
TypeScript is a static type checker, which means that it detects errors in code without running based on the types.

EveryDay Types: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html

*/